[package]
name = "alfons-assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26"
egui = "0.26"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"], optional = true }  # Делаем опциональным

[features]
default = []
persistence = ["serde"]