[package]
name = "app"
version = "0.0.5"
edition = "2024"

[dependencies]
eframe = { version = "0.29", features = ["persistence"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
open = "5.3"
